<a href="https://colab.research.google.com/github/Heet06/MLUP001/blob/main/Week-2/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

Numpy is a foundation of numerical computing in Python. It powers data analysis, machine learning and deep learning workflows.

#### Import Numpy

In [2]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.0.2


What is an "array"?

In programming, an array is a way to store and organize data — think of it like a list or table. In NumPy, arrays can have any number of dimensions:

1D: a list of values

2D: like a table (rows and columns)

3D: a stack of tables (like pages)

In NumPy, arrays are called ndarray (N-dimensional arrays)

Key rules: All items must be the same data type

The array has a fixed size

Shape must be regular (no jagged edges)

#### Creating arrays

1. From list:
  Create a numpy array from a Python list or from a sequence of elements

In [3]:
my_list = [1, 2, 3, 4, 5, 6]
print("Python list:", my_list)

array = np.array(my_list)
print("NumPy array:", array)

Python list: [1, 2, 3, 4, 5, 6]
NumPy array: [1 2 3 4 5 6]


In [4]:
print(array[0])

array[0] = 10
print(array)

b = array[:3]
print(b)

1
[10  2  3  4  5  6]
[10  2  3]


**Creating Arrays from Nested Lists**

Simulating small tabular datasets.

In [5]:
nested_list = [
    [1, 2, 3],
    [4, 5, 6]
]

multi_array = np.array(nested_list)
print("Multi-dimensional array:\n", multi_array)

Multi-dimensional array:
 [[1 2 3]
 [4 5 6]]


In NumPy, "axis" = dimension (e.g., rows = axis 0, columns = axis 1)

Access elements in muti-dimensional arrays like: a[row,column]

In [6]:
multi_array[1,2]

np.int64(6)

#### Array attributes

Key attributes of NumPy arrays:
  - `ndim`: number of dimensions
  - `shape`: dimensions along each axis
  - `size`: total number of elements in array
  - `dtype`: data type of elements

In [7]:
print("Type:", type(multi_array))
print("Number of dimensions:", multi_array.ndim)
print("Shape:", multi_array.shape)
print("Size:", multi_array.size)
print("Data Type:", multi_array.dtype)

Type: <class 'numpy.ndarray'>
Number of dimensions: 2
Shape: (2, 3)
Size: 6
Data Type: int64


#### Creating Basic Arrays

1. Create an array filled with 0's

In [8]:
zeros_1 = np.zeros(3)
zeros_2 = np.zeros((3, 3))
print(zeros_1)
print(zeros_2)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2. Creating an array filled with 1's:

In [9]:
ones_1 = np.ones(2)
ones_2 = np.ones((2, 4))
print(ones_1)
print(ones_2)

[1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. Creating an empty array:

In [10]:
np.empty(2)

array([1., 1.])

4. Create an array with a range of elements

In [11]:
range_arr = np.arange(4)
range_arr

array([0, 1, 2, 3])

5. Create an array with evenly spaced values:

Use np.arange(start, stop, step)

Create an array from 0 to 18 with step size 3.

In [12]:
range_arr =np.arange(0, 21, 3)
print(range_arr)

[ 0  3  6  9 12 15 18]


6. Create an array with evenly spaced values

Use np.linspace(start, stop, num)

In [13]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**Specifying your data type:**

Use the dtype keyword in NumPy to set the data type of an array.

Default: floating point (np.float64)

In [14]:
ones_1 = np.ones(2)
ones_1

array([1., 1.])

In [15]:
ones_1 = np.ones(2, dtype=np.int32)
ones_1

array([1, 1], dtype=int32)

#### Adding, Removing and Sorting Elements

**Sort:**

np.sort(arr) sorts values in ascending order

In [16]:
arr = np.array([2, 1, 5])
np.sort(arr)

array([1, 2, 5])

**Join arrays:**

np.concatenate((a,b)) joins arrays along an axis

In [18]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

**Remove**: Use indexing to select the elements you want to keep

#### Reshaping and Indexing