<a href="https://colab.research.google.com/github/Heet06/MLUP001/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

Numpy is a foundation of numerical computing in Python. It powers data analysis, machine learning and deep learning workflows.

#### Import Numpy

In [2]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.0.2


What is an "array"?

In programming, an array is a way to store and organize data — think of it like a list or table. In NumPy, arrays can have any number of dimensions:

1D: a list of values

2D: like a table (rows and columns)

3D: a stack of tables (like pages)

In NumPy, arrays are called ndarray (N-dimensional arrays)

Key rules: All items must be the same data type

The array has a fixed size

Shape must be regular (no jagged edges)

#### Creating arrays

1. From list:
  Create a numpy array from a Python list or from a sequence of elements

In [3]:
my_list = [1, 2, 3, 4, 5, 6]
print("Python list:", my_list)

array = np.array(my_list)
print("NumPy array:", array)

Python list: [1, 2, 3, 4, 5, 6]
NumPy array: [1 2 3 4 5 6]


In [4]:
print(array[0])

array[0] = 10
print(array)

b = array[:3]
print(b)

1
[10  2  3  4  5  6]
[10  2  3]


**Creating Arrays from Nested Lists**

Simulating small tabular datasets.

In [5]:
nested_list = [
    [1, 2, 3],
    [4, 5, 6]
]

multi_array = np.array(nested_list)
print("Multi-dimensional array:\n", multi_array)

Multi-dimensional array:
 [[1 2 3]
 [4 5 6]]


In NumPy, "axis" = dimension (e.g., rows = axis 0, columns = axis 1)

Access elements in muti-dimensional arrays like: a[row,column]

In [6]:
multi_array[1,2]

np.int64(6)

#### Array attributes

Key attributes of NumPy arrays:
  - `ndim`: number of dimensions
  - `shape`: dimensions along each axis
  - `size`: total number of elements in array
  - `dtype`: data type of elements

In [7]:
print("Type:", type(multi_array))
print("Number of dimensions:", multi_array.ndim)
print("Shape:", multi_array.shape)
print("Size:", multi_array.size)
print("Data Type:", multi_array.dtype)

Type: <class 'numpy.ndarray'>
Number of dimensions: 2
Shape: (2, 3)
Size: 6
Data Type: int64


#### Creating Basic Arrays

1. Create an array filled with 0's

In [8]:
zeros_1 = np.zeros(3)
zeros_2 = np.zeros((3, 3))
print(zeros_1)
print(zeros_2)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2. Creating an array filled with 1's:

In [9]:
ones_1 = np.ones(2)
ones_2 = np.ones((2, 4))
print(ones_1)
print(ones_2)

[1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. Creating an empty array:

In [10]:
np.empty(2)

array([1., 1.])

4. Create an array with a range of elements

In [11]:
range_arr = np.arange(4)
range_arr

array([0, 1, 2, 3])

5. Create an array with evenly spaced values:

Use np.arange(start, stop, step)

Create an array from 0 to 18 with step size 3.

In [12]:
range_arr =np.arange(0, 21, 3)
print(range_arr)

[ 0  3  6  9 12 15 18]


6. Create an array with evenly spaced values

Use np.linspace(start, stop, num)

In [13]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**Specifying your data type:**

Use the dtype keyword in NumPy to set the data type of an array.

Default: floating point (np.float64)

In [14]:
ones_1 = np.ones(2)
ones_1

array([1., 1.])

In [15]:
ones_1 = np.ones(2, dtype=np.int32)
ones_1

array([1, 1], dtype=int32)

#### Adding, Removing and Sorting Elements

**Sort:**

np.sort(arr) sorts values in ascending order

In [16]:
arr = np.array([2, 1, 5])
np.sort(arr)

array([1, 2, 5])

**Join arrays:**

np.concatenate((a,b)) joins arrays along an axis

In [18]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

**Remove**: Use indexing to select the elements you want to keep

#### Reshaping and Indexing

- Reshaping an array:
  Turn a 1D array with 12 elements into a 3x4 matrix.

In [19]:
arr = np.arange(12)
reshaped_arr = arr.reshape((3, 4))
print(reshaped_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
data = np.array([1, 2, 3])

print(data[1])

2


- Create an array from existing data

In [22]:
row = reshaped_arr[1]
col = reshaped_arr[:, -1]
print(row)
print(col)

[4 5 6 7]
[ 3  7 11]


#### Basic Operations

- Element-wise math operations:

In [23]:
data_1 = np.array([1, 2])
data_2 = np.array([3, 4])

# Element-wise Addition
data_3 = data_1 + data_2

In [24]:
data_3

array([4, 6])

In [29]:
# Element-wise Subtraction
data_3 = data_1 - data_2

In [30]:
data_3

array([-2, -2])

In [32]:
print("data_1 * data_2 :\n", data_1 * data_2)
print("data_2 / data_1 :\n", data_2 / data_1)

data_1 * data_2 :
 [3 8]
data_2 / data_1 :
 [3. 2.]


- Sum of elements:

In [33]:
data_1.sum()

np.int64(3)

- Sum by axis (for 2D arrays)

In [34]:
data_2 = np.array([[3, 1], [5, 2]])

data_2.sum(axis=0) # Column-wise

array([8, 3])

In [35]:
data_2.sum(axis=1) # Row-wise

array([4, 7])

**Broadcasting**

NumPy can automatically apply operations between arrays and scalars, or arrays of different shapes.

In [36]:
data_1

array([1, 2])

In [38]:
data_3 = data_1 * 5

In [39]:
data_3

array([ 5, 10])

#### Array Operations

- `min()`, `max()` and `sum()`

In [40]:
data = np.array([1, 5, 10, 3])

In [41]:
print(data.max())
print(data.min())
print(data.sum())

10
1
19


In [42]:
data = np.array([[2.1, 2.2], [3.4, 1.1]])
data

array([[2.1, 2.2],
       [3.4, 1.1]])

In [43]:
print(data.max())
print(data.min())
print(data.sum())

3.4
1.1
8.8


In [44]:
data.min(axis=0)

array([2.1, 1.1])

In [45]:
data.max(axis=1)

array([2.2, 3.4])

- `unique()` — use for obtain an array of unique values

In [47]:
arr = np.array([1, 1, 4, 5, 6, 7, 7, 4])
arr

array([1, 1, 4, 5, 6, 7, 7, 4])

In [49]:
unique_values = np.unique(arr)
print(unique_values)

[1 4 5 6 7]


**Flatten and Transpose in NumPy**

- Flattening a 2D array to 1D

In [51]:
x = np.array([[1, 2], [3, 4]])
print(x.flatten())

[1 2 3 4]


- Transposing arrays

In [52]:
print("Original:\n", x)
print("After transpose:\n")
print(x.T)

# or

print("After transpose method2:\n")
print(x.transpose())

Original:
 [[1 2]
 [3 4]]
After transpose:

[[1 3]
 [2 4]]
After transpose method2:

[[1 3]
 [2 4]]


**Statistical summary**

Calculate mean, median, standard deviation of a dataset

In [53]:
data = np.array([1, 3, 5, 7, 9])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Std Deviation:", np.std(data))

Mean: 5.0
Median: 5.0
Std Deviation: 2.8284271247461903


#### Handling Missing Data

- Using NaN for missing values:
  
  Calculate the mean of an array with missing values (use `np.nanmean(arr)`

In [55]:
data = np.array([8, np.nan, 10, 12])
print("Mean (skip nan):", np.nanmean(data))

Mean (skip nan): 10.0


### Challenge: Small Data Science Task

**Scenario:**

You have a dataset with some values missing. Calculate the mean after cleaning the data, then standardize it (subtract mean, divide by std deviation).

In [56]:
data = np.array([10, 15, np.nan, 25, 30])
mean_val = np.nanmean(data)
std_var = np.nanstd(data)
standardized = (data - mean_val) / std_var
print("Standardized:", standardized)

Standardized: [-1.26491106 -0.63245553         nan  0.63245553  1.26491106]


Note: np.nanstd computes standard deviation ignoring nan values.